name: Demo Workflow
on:
  push:
    branches:
      - main
env:
  GLOBAL_ENV: Production
jobs:
  test:
    environment: testing # Uncomment to use environment protection rules
    env:
      NODE_ENV: test
      MY_NAME: ${{secrets.MY_NAME}}
      USER_NAME: ${{secrets.USER_NAME}}
      PASSWORD: ${{secrets.PASSWORD}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache dependancies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-module-${{ hashFiles('**/package-lock.json') }}  
      # - name: Cache dependancies
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Lint Project
        run: npm run lint
      - name: Test Project
        continue-on-error: true
        id: run_tests
        run: npm test
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/test-report.json
      - name: Output information
        run: |
          echo "Node Version: $NODE_ENV"
          echo "My Name: $MY_NAME"
          echo "Global Environment: $GLOBAL_ENV"
          echo "Job Environment: $USER_NAME"
          echo "Password: $PASSWORD"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Cache dependancies
          uses: actions/cache@v3
          with:
            path: ~/.npm
            key: deps-node-module-${{ hashFiles('**/package-lock.json') }}  
        - name: Install dependencies
          run: npm ci

        - name: Build Project
          run: npm run build

        - name: Publish Html fIlename
          run: find dist -name "*.html"
          
        - name: Upload Build Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: dist-files
            path: dist
            # path: |
            #     dist
            #     package.json
  deploy:
    needs: build
    uses: ./.github/workflows/reusable.yml
    with:
      deploy_env: dist-files
    # secrets:
    #   SOME_SECRET: ${{ secrets.SOME_SECRET}}

  print-deploy-result:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Print deploy output
        run: |
          echo "${{ needs.deploy.outputs.result }}"
          echo "${{ needs.deploy.outputs.info }}"

  report:
    needs: [deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: output Information
        run: |
          echo "Something went wrong."
          echo "${{toJson(github)}}"