name : Deployment Exercise
on: [push, workflow_dispatch]
jobs:
# Multiple jobs for linting, testing, and deployment
  lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Load & Cache dependancies
          uses: ./.github/actions/cached-deps
        - name: Lint Project
          run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Load & Cache dependancies
        uses: ./.github/actions/cached-deps
      - name: Test Project
        id: run_tests
        run: npm test

      - name: Upload Build Artifacts
        if: failure() && steps.run_tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/test-report.json  
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Load & Cache dependancies
          uses: ./.github/actions/cached-deps

        - name: Build Project
          run: npm run build

        - name: Publish Html fIlename
          run: find dist -name "*.html"
          
        - name: Upload Build Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: dist-files
            path: dist
            # path: |
            #     dist
            #     package.json

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Load & Cache dependancies
        uses: ./.github/actions/cached-deps
      - name: Build Project
        run: npm run build
      - name: Deploy to Server
        run: echo "Deploying to server..."

  report:
    needs: [lint,deploy]
    if: failure() && needs.deploy.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: output Information
        run: |
          echo "Something went wrong."
          echo "${{toJson(github)}}"