name: Reusable Workflow
on: 
    workflow_call:
        inputs:
            deploy_env:
                description: 'The name of the deployable artifact files'
                required: false
                default: dist
                type: string
        outputs:
            result:
                description: 'The resutl oth the deployment operation'
                value: ${{jobs.deploy.outputs.outcome}}
        # secrets:
        #     SOME_SECRET:
        #         description: 'Deployment key for the target environment'    
        #         required: false
jobs:
    deploy:
        outputs:
            outcome: ${{ steps.set-result.outputs.result }}
        runs-on: ubuntu-latest
        steps:
            - name: Download Build Artifacts
              uses: actions/download-artifact@v4
              with:
                name: dist-files
            - name: Output contents of dist
              run: ls
            - name: Deploy Application
              run: echo "Deploying application..."
            - name: Set result output
              id: set-result
              run: |
               echo "result=Deployment completed successfully" >> "$GITHUB_OUTPUT"